apiVersion: v1
kind: Service
metadata:
  name: connect-portal-service
  labels:
    run: connect-portal-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    protocol: TCP
  - port: 443
    name: https
    protocol: TCP
  selector:
    app: connect-portal